/** Palavras comuns em português (substantivos) para o jogo. */
export const PALAVRAS = [
  "futebol", "panela", "avião", "linguiça", "cobertor", "bicicleta", "chocolate",
  "hospital", "guitarra", "praia", "relógio", "cachorro", "gato", "computador",
  "telefone", "cadeira", "mesa", "janela", "porta", "chave", "carro", "ônibus",
  "trem", "barco", "navio", "pizza", "hambúrguer", "sorvete", "café", "açúcar",
  "sal", "pimenta", "arroz", "feijão", "macarrão", "queijo", "leite", "ovo",
  "banana", "maçã", "laranja", "uva", "melancia", "abacaxi", "morango", "limão",
  "tomate", "cenoura", "batata", "cebola", "alho", "brócolis", "alface", "couve",
  "espelho", "toalha", "sabonete", "shampoo", "escova", "pasta", "fio dental",
  "travesseiro", "lençol", "edredom", "lâmpada", "ventilador", "ar-condicionado",
  "geladeira", "fogão", "micro-ondas", "liquidificador", "batedeira", "torradeira",
  "garfo", "faca", "colher", "prato", "copo", "jarra", "tigela", "frigideira",
  "televisão", "controle", "videogame", "tablet", "câmera", "impressora", "roteador",
  "livro", "caderno", "caneta", "lápis", "borracha", "régua", "mochila", "guarda-chuva",
  "boné", "chapéu", "cachecol", "luva", "meia", "sapato", "tênis", "sandália",
  "calça", "camisa", "vestido", "jaqueta", "óculos", "relógio", "bolsa", "carteira",
  "ônibus", "metrô", "táxi", "moto", "patinete", "skate", "patins", "pipa",
  "parque", "escola", "igreja", "banco", "farmácia", "padaria", "mercado", "shopping",
  "cinema", "teatro", "estádio", "piscina", "floresta", "montanha", "rio", "cachoeira",
  "vulcão", "deserto", "ilha", "farol", "castelo", "ponte", "túnel", "aeroporto",
  "estação", "hotel", "restaurante", "biblioteca", "museu", "zoológico", "aquário",
  "leão", "tigre", "elefante", "girafa", "zebra", "hipopótamo", "rinoceronte", "macaco",
  "papagaio", "coruja", "águia", "pombo", "pato", "galinha", "porco", "vaca",
  "cavalo", "ovelha", "cabra", "coelho", "rato", "cobra", "jacaré", "tartaruga",
  "peixe", "baleia", "golfinho", "polvo", "caranguejo", "lagosta", "camarão",
  "formiga", "abelha", "borboleta", "aranha", "mosquito", "barata", "lesma",
  "flor", "árvore", "grama", "cacto", "samambaia", "rosa", "girassol", "orquídea",
  "sol", "lua", "estrela", "nuvem", "arco-íris", "neve", "chuva", "vento",
  "terremoto", "tornado", "furacão", "raio", "trovão", "arco", "ponte", "estrada",
  "mapa", "bússola", "binóculos", "telescópio", "microscópio", "bateria", "pilha",
  "martelo", "prego", "parafuso", "chave de fenda", "alicate", "serrote", "furadeira",
  "tinta", "pincel", "tela", "argila", "violão", "piano", "bateria", "flauta",
  "trompete", "saxofone", "violino", "harpa", "acordeão", "xilofone", "castanholas",
  "fantasma", "robô", "astronauta", "pirata", "ninja", "cowboy", "detetive", "médico",
  "bombeiro", "policial", "chef", "pintor", "músico", "ator", "cientista", "professor",
  "futebol", "vôlei", "basquete", "tênis", "natação", "atletismo", "boxe", "judô",
  "xadrez", "damas", "dominó", "baralho", "dado", "pião", "quebra-cabeça", "lego",
  "boneca", "carrinho", "boneco", "urso", "pelúcia", "pipoca", "refrigerante",
  "suco", "água", "chá", "vinho", "cerveja", "biscoito", "bolo", "torta", "pudim",
  "mousse", "brigadeiro", "beijinho", "cocada", "paçoca", "rapadura", "goiabada",
  "geleia", "mel", "manteiga", "iogurte", "requeijão", "presunto", "mortadela",
  "salsicha", "bacon", "peixe", "frango", "carne", "costela", "picanha", "alcatra",
  "coração", "pulmão", "fígado", "cérebro", "osso", "músculo", "pele", "cabelo",
  "unha", "dente", "língua", "nariz", "orelha", "olho", "sobrancelha", "cotovelo",
  "joelho", "tornozelo", "dedo", "mão", "pé", "ombro", "costas", "barriga",
  "anel", "colar", "brinco", "pulseira", "pingente", "corrente", "broche", "tiara",
  "espada", "escudo", "lança", "arco", "flecha", "machado", "besta", "canhão",
  "torre", "muralha", "portão", "grade", "cerca", "jardim", "horta", "celeiro",
  "fazenda",
].filter((p, i, a) => a.indexOf(p) === i);

export function palavraAleatoria() {
  const i = Math.floor(Math.random() * PALAVRAS.length);
  return PALAVRAS[i];
}
